name: EN
options:
  developmentLanguage: "en"
packages:
  Reachability:
    path: vendor/Reachability.swift
  SnapKit:
    path: vendor/SnapKit
  Lottie:
    path: vendor/lottie-ios
  SnapshotTesting:
    path: vendor/swift-snapshot-testing
  ZIPFoundation:
    path: vendor/ZIPFoundation
  CocoaLumberjack:
    path: vendor/CocoaLumberjack
targets:
  EN:
    platform: iOS
    type: application
    deploymentTarget: "11.0"
    sources:
      - path: Sources/EN
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: nl.rijksoverheid.en
        SWIFT_VERSION: 5.2
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: C2H38GV99H
        ENABLE_BITCODE: YES
        TARGETED_DEVICE_FAMILY: 1
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: C2H38GV99H
        SWIFT_OBJC_BRIDGING_HEADER: Sources/EN/AppBridge/EN-Bridging-Header.h
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          CODE_SIGN_ENTITLEMENTS: Sources/EN/Resources/Entitlements/Debug.entitlements
          PROVISIONING_PROFILE_SPECIFIER: "EN Tracing development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          CODE_SIGN_ENTITLEMENTS: Sources/EN/Resources/Entitlements/Release.entitlements
          PROVISIONING_PROFILE_SPECIFIER: "EN Tracing development"
    info:
      path: Sources/EN/Resources/Info.plist
      properties:
        NSBluetoothPeripheralUsageDescription: "To securely exchange unique id's"
        BGTaskSchedulerPermittedIdentifiers: [$(PRODUCT_BUNDLE_IDENTIFIER).exposure-notification]
        CFBundleName: CoronaMelder
        CFBundleDisplayName: CoronaMelder
        CFBundleShortVersionString: "0.1"
        CFBundleVersion: "1.0"
        CFBundleIconName: "Media.xcassets/AppIcon.appiconset"
        ITSAppUsesNonExemptEncryption: false
        LSApplicationQueriesSchemes: [""]
        LSRequiresIPhoneOS: true
        UIAppFonts: []
        UIBackgroundModes: [fetch, processing]
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: [armv7, bluetooth-le, telephony]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIViewControllerBasedStatusBarAppearance: true
        UIUserInterfaceStyle: "Light"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
                UISceneConfigurationName: Default Configuration
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        BGTaskSchedulerPermittedIdentifiers:
          - "nl.rijksoverheid.en.background-update"
        NETWORK_CONFIGURATION: ${NETWORK_CONFIGURATION}
        LOG_LEVEL: ${LOG_LEVEL}
    dependencies:
      - target: ENCore
        link: false
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: ENCoreTests
          parallelizable: false
          randomExecutionOrder: true
  ENCore:
    platform: iOS
    type: framework
    deploymentTarget: "13.5"
    sources:
      - Sources/ENCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: nl.rijksoverheid.en.core
        TARGETED_DEVICE_FAMILY: 1
        SWIFT_VERSION: 5.2
        OTHER_LDFLAGS: -weak_framework ExposureNotification
    dependencies:
      - package: CocoaLumberjack
        product: CocoaLumberjack
      - package: CocoaLumberjack
        product: CocoaLumberjackSwift
      - package: ZIPFoundation
      - package: SnapKit
      - package: Lottie
      - package: Reachability
      - sdk: ExposureNotification.framework
        optional: true
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: ENCoreTests
          parallelizable: false
          randomExecutionOrder: true
  ENCoreTests:
    platform: iOS
    type: bundle.unit-test
    deploymentTarget: "13.5"
    sources:
      - Sources/ENCoreUnitTests
    dependencies:
      - target: ENCore
      - package: SnapshotTesting
    settings:
      base:
        SWIFT_VERSION: 5.2
    preBuildScripts:
      - path: tools/scripts/generate-mocks.sh
        name: Generate Mocks
